services:
  web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  background-jobs:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  permit-worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
