/**
 * Sample contract data for development/demo purposes.
 * Replace with real API loader when backend is wired up.
 */
import type { PipelineContract } from "./types";

export const SAMPLE_CONTRACTS: PipelineContract[] = [
  {
    id: "c-001",
    subject: "Sun Health La Loma RGS",
    contractor: "PWI Construction",
    receivedDate: "2026-01-20",
    attachmentCount: 3,
    stage: "done",
    estimateTotal: 20_518.5,
    contractTotal: 20_168.5,
    mathCheck: {
      estimateTotal: 20_518.5,
      contractTotal: 20_168.5,
      removedTotal: 1350,
      addedTotal: 1000,
      calculated: 20_168.5,
      variance: 0,
      matches: true,
    },
    outcome: "RECONCILED",
    flags: [],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-002",
    subject: "Embrey Greenway SWPPP",
    contractor: "Weis Builders",
    receivedDate: "2026-01-22",
    attachmentCount: 4,
    stage: "reconciled",
    estimateTotal: 34_250,
    contractTotal: 31_800,
    mathCheck: {
      estimateTotal: 34_250,
      contractTotal: 31_800,
      removedTotal: 3200,
      addedTotal: 750,
      calculated: 31_800,
      variance: 0,
      matches: true,
    },
    outcome: "RECONCILED",
    flags: [
      {
        type: "EXPLICIT_RETENTION",
        description: "Retention percentage not explicitly stated in contract",
        severity: "info",
      },
    ],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-003",
    subject: "Verge at Ballpark Village",
    contractor: "Weis Builders",
    receivedDate: "2026-01-18",
    attachmentCount: 2,
    stage: "validated",
    estimateTotal: 45_600,
    contractTotal: 42_100,
    mathCheck: null,
    outcome: null,
    flags: [
      {
        type: "MISSING_MOBILIZATION",
        description: "BMP install items present but no mobilization line item",
        severity: "error",
      },
      {
        type: "INSPECTION_QUANTITY_UNCLEAR",
        description: "Contract says 'inspections' without specifying count",
        severity: "warning",
      },
    ],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-004",
    subject: "Desert Sky Phase 2 Grading",
    contractor: "Sunbelt Holdings",
    receivedDate: "2026-01-24",
    attachmentCount: 5,
    stage: "extracted",
    estimateTotal: 78_900,
    contractTotal: 76_350,
    mathCheck: null,
    outcome: null,
    flags: [],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-005",
    subject: "Sprouts Rita Ranch Erosion",
    contractor: "Kitchell Contractors",
    receivedDate: "2026-01-25",
    attachmentCount: 3,
    stage: "collected",
    estimateTotal: 15_200,
    contractTotal: null,
    mathCheck: null,
    outcome: null,
    flags: [],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-006",
    subject: "Muscular Moving Men Dust Control",
    contractor: "Haydon Building",
    receivedDate: "2026-01-26",
    attachmentCount: 2,
    stage: "queue",
    estimateTotal: 8750,
    contractTotal: null,
    mathCheck: null,
    outcome: null,
    flags: [],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-007",
    subject: "Pima Medical Institute Expansion",
    contractor: "Lloyd Construction",
    receivedDate: "2026-01-23",
    attachmentCount: 4,
    stage: "queue",
    estimateTotal: 52_300,
    contractTotal: null,
    mathCheck: null,
    outcome: null,
    flags: [],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-008",
    subject: "Tucson Premium Outlets Landscape",
    contractor: "Ryan Companies",
    receivedDate: "2026-01-21",
    attachmentCount: 6,
    stage: "validated",
    estimateTotal: 125_000,
    contractTotal: 118_500,
    mathCheck: null,
    outcome: null,
    flags: [
      {
        type: "TUCSON_NO_ROCK",
        description: "Tucson project has rock entrance items - must be struck",
        severity: "error",
      },
      {
        type: "NO_FINES_LIABILITY",
        description:
          "Contract includes 'assume responsibility for fines' language",
        severity: "error",
      },
    ],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-009",
    subject: "Marana Heritage District Park",
    contractor: "Sundt Construction",
    receivedDate: "2026-01-19",
    attachmentCount: 3,
    stage: "done",
    estimateTotal: 67_800,
    contractTotal: 65_200,
    mathCheck: {
      estimateTotal: 67_800,
      contractTotal: 65_200,
      removedTotal: 4100,
      addedTotal: 1500,
      calculated: 65_200,
      variance: 0,
      matches: true,
    },
    outcome: "RECONCILED",
    flags: [],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-010",
    subject: "Oro Valley Marketplace Drainage",
    contractor: "Bourn Companies",
    receivedDate: "2026-01-24",
    attachmentCount: 2,
    stage: "extracted",
    estimateTotal: 22_100,
    contractTotal: 21_500,
    mathCheck: null,
    outcome: null,
    flags: [],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-011",
    subject: "Sentinel Peak Water Reclamation",
    contractor: "Granite Construction",
    receivedDate: "2026-01-17",
    attachmentCount: 5,
    stage: "done",
    estimateTotal: 89_400,
    contractTotal: 87_200,
    mathCheck: {
      estimateTotal: 89_400,
      contractTotal: 87_200,
      removedTotal: 3500,
      addedTotal: 1300,
      calculated: 87_200,
      variance: 0,
      matches: true,
    },
    outcome: "RECONCILED",
    flags: [],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-012",
    subject: "Campbell Ave Road Widening SWPPP",
    contractor: "Ames Construction",
    receivedDate: "2026-01-26",
    attachmentCount: 3,
    stage: "queue",
    estimateTotal: 31_500,
    contractTotal: null,
    mathCheck: null,
    outcome: null,
    flags: [],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-013",
    subject: "Rillito Regional Park Improvements",
    contractor: "Haydon Building",
    receivedDate: "2026-01-15",
    attachmentCount: 4,
    stage: "reconciled",
    estimateTotal: 41_200,
    contractTotal: 39_800,
    mathCheck: {
      estimateTotal: 41_200,
      contractTotal: 39_800,
      removedTotal: 2400,
      addedTotal: 1000,
      calculated: 39_800,
      variance: 0,
      matches: true,
    },
    outcome: "RECONCILED",
    flags: [
      {
        type: "CERT_PAYROLL_TYPE",
        description:
          "Certified payroll type not specified - assume Davis-Bacon",
        severity: "warning",
      },
    ],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-014",
    subject: "Civano Master-Planned Community",
    contractor: "Meritage Homes",
    receivedDate: "2026-01-22",
    attachmentCount: 7,
    stage: "collected",
    estimateTotal: 156_000,
    contractTotal: null,
    mathCheck: null,
    outcome: null,
    flags: [],
    notionUrl: null,
    mondayUrl: null,
  },
  {
    id: "c-015",
    subject: "Tangerine Road Widening Phase 3",
    contractor: "Granite Construction",
    receivedDate: "2026-01-20",
    attachmentCount: 4,
    stage: "extracted",
    estimateTotal: 94_500,
    contractTotal: 91_200,
    mathCheck: null,
    outcome: null,
    flags: [],
    notionUrl: null,
    mondayUrl: null,
  },
];
