import { documentReviewWorkspaceSchema } from "@/features/documents/document-model";
import type { DocumentReviewWorkspace } from "@/features/documents/document-model";

export const documentReviewSampleData: DocumentReviewWorkspace =
  documentReviewWorkspaceSchema.parse({
    items: [
      {
        canPreview: true,
        canRerun: true,
        createdAt: "2026-03-20T15:15:00.000Z",
        documentType: "contract",
        emailId: 986_212,
        emailSubject: "Contract draft for Falco Aluminum",
        extractedFields: [
          { label: "Counterparty", value: "Waltz Construction" },
          { label: "Project", value: "FALCO ALUMINUM" },
          { label: "Redline state", value: "Contractor comments received" },
        ],
        extractionStatus: "success",
        fileName: "Prime Contract Draft.pdf",
        id: 300_901,
        keySignals: [
          "Contains indemnity redlines",
          "References owner-supplied insurance exhibit",
          "Ready for contract review triage",
        ],
        previewLabel: "Inline PDF preview available",
        projectId: 1441,
        projectName: "FALCO ALUMINUM",
        qaStatus: "needs_work",
        source: "email_attachment",
        summary:
          "Draft contract from the GC with redlines that need legal/ops review before the project can move forward.",
        updatedAt: "2026-03-21T01:55:22.947Z",
      },
      {
        canPreview: true,
        canRerun: true,
        createdAt: "2026-03-19T10:20:00.000Z",
        documentType: "dust_permit",
        emailId: 986_330,
        emailSubject: "Permit packet for Falco Aluminum",
        extractedFields: [
          { label: "Permit authority", value: "Maricopa County" },
          { label: "Application state", value: "Requested" },
          { label: "Project", value: "FALCO ALUMINUM" },
        ],
        extractionStatus: "pending",
        fileName: "Dust Permit Packet.pdf",
        id: 301_024,
        keySignals: [
          "Packet uploaded from email",
          "Awaiting extraction pipeline completion",
          "Should link back to dust permit workflow",
        ],
        previewLabel: "Processing preview",
        projectId: 1441,
        projectName: "FALCO ALUMINUM",
        qaStatus: "unreviewed",
        source: "email_attachment",
        summary:
          "Permit packet tied to the active project workflow. The file is present, but extraction still needs to finish.",
        updatedAt: "2026-03-21T01:40:12.000Z",
      },
      {
        canPreview: true,
        canRerun: true,
        createdAt: "2026-03-18T09:30:00.000Z",
        documentType: "addenda",
        emailId: 986_355,
        emailSubject: "PRIEST & ALAMEDA BLDG 2 bid clarification",
        extractedFields: [
          { label: "Document family", value: "Addendum" },
          { label: "Project", value: "PRIEST & ALAMEDA BLDG 2" },
          { label: "Extraction profile", value: "parsed" },
        ],
        extractionStatus: "success",
        fileName: "Bid Addendum 02.pdf",
        id: 300_915,
        keySignals: [
          "Project-linked plan addendum",
          "Useful for estimate context and scope changes",
          "Needs downstream estimate/project association",
        ],
        previewLabel: "Inline PDF preview available",
        projectId: 3836,
        projectName: "PRIEST & ALAMEDA BLDG 2",
        qaStatus: "unreviewed",
        source: "parsed",
        summary:
          "Successful parse of a bid addendum that likely affects scope, assumptions, or downstream estimate comparison.",
        updatedAt: "2026-03-20T17:45:00.000Z",
      },
      {
        canPreview: true,
        canRerun: true,
        createdAt: "2026-03-18T09:32:00.000Z",
        documentType: "plan_set",
        emailId: 986_355,
        emailSubject: "PRIEST & ALAMEDA BLDG 2 bid clarification",
        extractedFields: [
          { label: "Failure mode", value: "Unreadable OCR output" },
          { label: "Source", value: "email_attachment" },
        ],
        extractionStatus: "failed",
        fileName: "Civil Plan Set.pdf",
        id: 300_916,
        keySignals: [
          "High-value failure because it blocks downstream review",
          "Candidate for rerun with OCR/full analysis",
        ],
        previewLabel: "Original file available for inspection",
        projectId: 3836,
        projectName: "PRIEST & ALAMEDA BLDG 2",
        qaStatus: "unreviewed",
        source: "email_attachment",
        summary:
          "Plan set failed extraction and should probably be rerun with a more aggressive profile before anyone triages it manually.",
        updatedAt: "2026-03-20T17:44:00.000Z",
      },
      {
        canPreview: true,
        canRerun: true,
        createdAt: "2026-03-05T10:33:52.742Z",
        documentType: "estimate",
        emailId: 986_265,
        emailSubject:
          'FW: SWPPP Estimate for "STREET MODERNIZATION PROJECT 3RD AND 5TH AVENUES - WASHINGTON ST TO MCDOWELL ST" from Desert Services & SWPP Solutions',
        extractedFields: [
          { label: "Document family", value: "Estimate PDF" },
          { label: "QA state", value: "Needs manual review" },
        ],
        extractionStatus: "failed",
        fileName: "Desert Services Proposal.pdf",
        id: 300_635,
        keySignals: [
          "Email attachment",
          "No linked project yet",
          "Could become either estimate context or stray inbox artifact",
        ],
        previewLabel: "Original file available for inspection",
        projectId: null,
        projectName: null,
        qaStatus: "unreviewed",
        source: "email_attachment",
        summary:
          "Attachment from the inbox that has not been associated with a project yet. Good example of a document that needs project/email linking.",
        updatedAt: "2026-03-21T01:55:22.911Z",
      },
      {
        canPreview: true,
        canRerun: false,
        createdAt: "2026-03-17T11:00:00.000Z",
        documentType: "estimate",
        emailId: null,
        emailSubject: null,
        extractedFields: [
          {
            label: "Project",
            value: "BANNER - PAYSON RADIATION ONCOLOGY EXPANSION",
          },
          { label: "QA state", value: "Approved" },
          { label: "Source", value: "parsed" },
        ],
        extractionStatus: "success",
        fileName: "Banner Payson Proposal.pdf",
        id: 300_777,
        keySignals: [
          "Already approved",
          "Links directly to a known project",
          "Useful as a control example for the queue",
        ],
        previewLabel: "Preview approved output",
        projectId: 3,
        projectName: "BANNER - PAYSON RADIATION ONCOLOGY EXPANSION",
        qaStatus: "approved",
        source: "parsed",
        summary:
          "An approved parsed document that shows what a stable end-state item looks like in the review queue.",
        updatedAt: "2026-03-18T12:12:00.000Z",
      },
    ],
  });
