default:
    @just --list

ocr pdf_path:
    uv --directory ../apps/pdf-analysis run plan-ocr gemini-ocr {{pdf_path}}

ocr-limit pdf_path max_pages:
    uv --directory ../apps/pdf-analysis run plan-ocr gemini-ocr {{pdf_path}} --max-pages {{max_pages}}

status:
    uv --directory ../apps/pdf-analysis run pdf-analysis status
