import { projectWorkspaceSchema } from "@/features/projects/project-model";
import type { ProjectWorkspace } from "@/features/projects/project-model";

export const projectWorkspaceSampleData: ProjectWorkspace =
  projectWorkspaceSchema.parse({
    projects: [
      {
        awardedValue: 42_150,
        bidStatus: "Won",
        bidValue: 42_150,
        canonicalEstimateId: 2274,
        contractStatus: "Need Contract",
        contractor: "Waltz Construction",
        documentCount: 12,
        documents: [
          {
            documentType: "estimate",
            extractionStatus: "success",
            fileName: "Desert Services Proposal.pdf",
            id: 300_635,
            qaStatus: "needs_work",
          },
          {
            documentType: "contract",
            extractionStatus: "success",
            fileName: "Prime Contract Draft.pdf",
            id: 300_901,
            qaStatus: "unreviewed",
          },
          {
            documentType: "dust_permit",
            extractionStatus: "pending",
            fileName: "Dust Permit Packet.pdf",
            id: 301_024,
            qaStatus: "unreviewed",
          },
        ],
        dustPermitStatus: "Requested",
        emailCount: 18,
        emails: [
          {
            fromEmail: "pm@waltzconstruction.com",
            id: 986_212,
            receivedAt: "2026-03-20T15:15:00.000Z",
            subject: "Contract draft for Falco Aluminum",
          },
          {
            fromEmail: "estimating@desertservices.net",
            id: 986_265,
            receivedAt: "2026-03-20T10:41:00.000Z",
            subject: "Updated proposal and schedule assumptions",
          },
        ],
        estimateName: "FALCO ALUMINUM",
        estimateNumber: "3222402",
        lastTouchAt: "2026-03-21T01:55:22.947Z",
        nextAction:
          "Review contract redlines and attach the final permit packet.",
        noiStatus: "Requested",
        projectId: 1441,
        projectName: "FALCO ALUMINUM",
        safetyStatus: "Requested",
      },
      {
        awardedValue: 28_745,
        bidStatus: "Won",
        bidValue: 28_745,
        canonicalEstimateId: 2169,
        contractStatus: "Negotiating",
        contractor: "Derek Builders - General Contractor",
        documentCount: 6,
        documents: [
          {
            documentType: "contract",
            extractionStatus: "success",
            fileName: "Owner Contract Markup.pdf",
            id: 300_811,
            qaStatus: "approved",
          },
          {
            documentType: "safety_packet",
            extractionStatus: "success",
            fileName: "Site Safety Requirements.pdf",
            id: 300_812,
            qaStatus: "unreviewed",
          },
        ],
        dustPermitStatus: "Not Needed",
        emailCount: 9,
        emails: [
          {
            fromEmail: "contracts@derekbuilders.com",
            id: 986_300,
            receivedAt: "2026-03-19T18:05:00.000Z",
            subject: "ECHO contract comments",
          },
        ],
        estimateName: "ECHO",
        estimateNumber: "4252406",
        lastTouchAt: "2026-03-20T19:15:00.000Z",
        nextAction:
          "Respond to contract comments and confirm if safety packet is complete.",
        noiStatus: "Done",
        projectId: 1387,
        projectName: "ECHO",
        safetyStatus: "Done",
      },
      {
        awardedValue: null,
        bidStatus: "Bid Sent",
        bidValue: 28_905,
        canonicalEstimateId: 117_035,
        contractStatus: "Pending",
        contractor: "Wespac Construction Inc.",
        documentCount: 3,
        documents: [
          {
            documentType: "addenda",
            extractionStatus: "success",
            fileName: "Bid Addendum 02.pdf",
            id: 300_915,
            qaStatus: "unreviewed",
          },
          {
            documentType: "plan_set",
            extractionStatus: "failed",
            fileName: "Civil Plan Set.pdf",
            id: 300_916,
            qaStatus: "unreviewed",
          },
        ],
        dustPermitStatus: "Submitted",
        emailCount: 11,
        emails: [
          {
            fromEmail: "estimating@wespac.com",
            id: 986_355,
            receivedAt: "2026-03-18T09:30:00.000Z",
            subject: "PRIEST & ALAMEDA BLDG 2 bid clarification",
          },
        ],
        estimateName: "PRIEST & ALAMEDA BLDG 2",
        estimateNumber: "000106",
        lastTouchAt: "2026-03-18T17:10:00.000Z",
        nextAction: "Confirm permit filing and retry failed plan extraction.",
        noiStatus: "Requested",
        projectId: 3836,
        projectName: "PRIEST & ALAMEDA BLDG 2",
        safetyStatus: "Not Needed",
      },
      {
        awardedValue: null,
        bidStatus: "Bid Sent",
        bidValue: 23_030,
        canonicalEstimateId: 27_727,
        contractStatus: "Pending",
        contractor: "Guthrie General, Inc.",
        documentCount: 1,
        documents: [
          {
            documentType: "estimate",
            extractionStatus: "success",
            fileName: "Banner Payson Proposal.pdf",
            id: 300_777,
            qaStatus: "approved",
          },
        ],
        dustPermitStatus: "Not Needed",
        emailCount: 8,
        emails: [
          {
            fromEmail: "pm@guthriegc.com",
            id: 986_401,
            receivedAt: "2026-03-17T12:12:00.000Z",
            subject: "Banner Payson schedule and contract timing",
          },
        ],
        estimateName: "BANNER - PAYSON RADIATION ONCOLOGY EXPANSION",
        estimateNumber: "000012",
        lastTouchAt: "2026-03-17T12:12:00.000Z",
        nextAction:
          "Wait for contract request from contractor and monitor inbox.",
        noiStatus: "Done",
        projectId: 3,
        projectName: "BANNER - PAYSON RADIATION ONCOLOGY EXPANSION",
        safetyStatus: "Not Needed",
      },
    ],
  });
